import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  html: {
    height: '100%',
  },
  body: {
    backgroundColor: '#666',
    fontFamily: '"Roboto", sans-serif',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontSize: 24,
    lineHeight: 28,
  },
  content: {
    backgroundColor: '#fff',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 50,
    padding: 12,
    width: 621,
    height: 457,
  },
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    borderBottomColor: '#000',
    borderBottomWidth: 1,
    width: '100%',
    height: '100%',
    maxHeight: 100,
  },
  search__search_input: {
    width: '100%',
    height: 45,
    paddingTop: 11,
    paddingRight: 0,
    paddingBottom: 13,
    paddingLeft: 16,
    borderBottomColor: '#000',
    borderBottomWidth: 1,
    backgroundColor: 'transparent',
  },
  search__search_input_error: {
    backgroundColor: 'rgba(219, 65, 65, 0.322)',
  },
  blocks: {
    display: 'flex',
  },
  weather: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    width: '50%',
  },
  tab: {
    height: '100%',
  },
  tab__grad__after: {
    // content: "°",
  },
  tab_now: {
    display: 'flex',
    flexDirection: 'column',
  },
  tab_now_active: {
    display: 'flex',
  },
  tab_now__temperature: {
    marginTop: 20,
    marginRight: 20,
    marginBottom: 20,
    marginLeft: 20,
    height: 95,
    fontSize: 70,
    lineHeight: 82,
  },
  tab_now__img_wrap: {
    alignSelf: 'center',
  },
  tab_now__weather_img: {
    objectFit: 'cover',
    // filter: 'drop-shadow(0px 0px 3px rgba(0, 0, 0, 0.7))',
  },
  tab_now__bottom: {
    marginTop: 'auto',
    minHeight: 50,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  tab_now__bottom__location_name: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 17,
    marginLeft: 12,
  },
  tab_now__bottom__like_btn: {
    padding: 0,
    marginTop: 0,
    marginRight: 26,
    marginBottom: 23,
    marginLeft: 0,
    width: 25,
    height: 25,
    // background: 'url(../img/like.svg) no-repeat center',
  },
  // tab_now__bottom__like_btn_hover: {
  //   background: 'url(../img/like_active.svg) no-repeat center',
  // },
  // tab_now__bottom__like_btn_active: {
  //   background: 'url(../img/like_active.svg) no-repeat center',
  // },
  // tab_now__bottom__like_btn_active_hover: {
  //   background: 'url(../img/like.svg) no-repeat center',
  // },
  tab_details: {
    textAlign: 'left',
  },
  tab_details_active: {
    display: 'flex',
    flexDirection: 'column',
  },
  tab_details__location_name: {
    marginTop: 33,
    marginRight: 0,
    marginBottom: 42,
    marginLeft: 17,
  },
  tab_details__details_list: {
    marginLeft: 15,
    lineHeight: 28,
  },
  tab_forecast: {
    paddingTop: 33,
    paddingRight: 16,
    paddingBottom: 0,
    paddingLeft: 14,
    flexDirection: 'column',
    maxHeight: 345,
    // overflowY: 'auto',
  },
  tab_forecast_active: {
    display: 'flex',
  },
  tab_forecast__time_block: {
    fontSize: 18,
    lineHeight: 21,
    marginBottom: 9,
    paddingTop: 6,
    paddingRight: 12,
    paddingBottom: 13,
    paddingLeft: 10,
    borderBottomColor: '#000',
    borderBottomWidth: 1,
    width: 265,
    height: 120,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  tab_forecast__time_block_bot: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
  },
  tab_forecast__time_block_top: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
  },
  tab_forecast__time_block_weather: {
    textAlign: 'center',
  },
  tab_forecast__weather_img: {
    marginTop: -10,
    marginRight: -10,
    marginBottom: -10,
    marginLeft: -10,
    width: 40,
    height: 40,
    // filter: 'drop-shadow(0px 0px 2px rgba(0, 0, 0, 0.7))',
  },
  tab_nav: {
    display: 'flex',
    // justifySelf: 'flex-end',
    justifyContent: 'flex-end',
  },
  tab_nav_button: {
    borderTopColor: '#000',
    borderTopWidth: 1,
    width: '100%',
    backgroundColor: '#fff',
    verticalAlign: 'middle',
    fontSize: 18,
    lineHeight: 21,
    // textDecoration: 'none',
    textDecorationLine: 'none',
    color: '#000',
    height: 41,
    borderRightColor: '#000',
    borderRightWidth: 1,
  },
  tab_nav_button_last_child: {
    borderRightWidth: 0,
  },
  tab_nav_button_hover: {
    backgroundColor: '#8685853d',
  },
  tab_nav__active: {
    color: '#fff',
    backgroundColor: '#000',
  },
  tab_nav__active_hover: {
    backgroundColor: '#000',
  },
  locations: {
    width: '50%',
    textAlign: 'left',
    borderLeftColor: '#000',
    borderLeftWidth: 1,
  },
  locations__block_name: {
    paddingTop: 33,
    paddingRight: 0,
    paddingBottom: 7,
    paddingLeft: 18,
    borderBottomColor: '#000',
    borderBottomWidth: 1,
  },
  locations__locations_list: {
    marginTop: 35,
    marginRight: 18,
    marginBottom: 0,
    marginLeft: 18,
    height: '100%',
    maxHeight: 250,
    // overflow: 'auto',
  },
  locations__locations_list_li: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  locations__locations_list_li__liked_location: {
    backgroundColor: 'transparent',
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    textAlign: 'left',
    width: '100%',
  },
  locations__locations_list_li__delete_location: {
    verticalAlign: 'middle',
    width: 27,
    height: 27,
    // background: 'url(../img/cross.svg) no-repeat center',
  },
  locations__locations_list_li__delete_location_hover: {
    backgroundColor: '#8685853d',
  },
  locations__locations_list_li_hover: {
    backgroundColor: '#8685853d',
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    textAlign: 'center',
    backgroundColor: '#BD8CF3',
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.5)',
  },
});
